[server]
runOnSave = true
fileWatcherType = "poll"

address ="0.0.0.0"
port = 8501
baseUrlPath = ""

[browser]

# Internet address where users should point their browsers in order to
# connect to the app. Can be IP address or DNS name and path.

# This is used to:
# - Set the correct URL for CORS and XSRF protection purposes.
# - Show the URL on the terminal
# - Open the browser

# Default: "localhost"
# serverAddress = "0.0.0.0"

[client]
showErrorDetails = false
# TODO: prod config
